/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-11-08 10:01:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class checktest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head><title>입력창 만들기</title></head>\r\n");
      out.write("<body>\r\n");
      out.write("<FORM>\r\n");
      out.write("<h3>type: text</h3>\r\n");
      out.write("<input type=\"text\" name=\"user\" size=\"10\" maxlength=\"10\" value=\"kim\"><p>\r\n");
      out.write("<h3>type: password</h3>\r\n");
      out.write("<input type=\"password\" name=\"pwd\" size=\"20\" maxlength=\"10\">\r\n");
      out.write("<h3>type: checkbox</h3>\r\n");
      out.write("<input type=\"checkbox\" name=\"HELLO\" value=\"goodmoning\" checked>아침인사\r\n");
      out.write("<input type=\"checkbox\" name=\"HELLO\" value=\"goodafternoon\">점심인사\r\n");
      out.write("<input type=\"checkbox\" name=\"HELLO\" value=\"goodbye\">저녁인사\r\n");
      out.write("<h3>type: radio</h3>\r\n");
      out.write("<input type=\"radio\" name=\"fruit\" value=\"apple\" checked>사과\r\n");
      out.write("<input type=\"radio\" name=\"fruit\" value=\"banana\">바나나\r\n");
      out.write("<input type=\"radio\" name=\"fruit\" value=\"peach\">복숭아\r\n");
      out.write("<h3>type: file</h3>\r\n");
      out.write("<input type=\"file\">\r\n");
      out.write("<h3>type: submit</h3>\r\n");
      out.write("<input type=\"submit\"><P>\r\n");
      out.write("<input type=\"submit\" value=\"전송\">\r\n");
      out.write("<h3>type: reset</h3>\r\n");
      out.write("<input type=\"text\">이름<br>\r\n");
      out.write("<input type=\"text\">주소<br>\r\n");
      out.write("<input type=\"reset\" value=\"초기화\"><input type=\"submit\" value=\"전송\">\r\n");
      out.write("<h3>type: button</h3>\r\n");
      out.write("<input type=\"button\" value=\"버튼이에요\"><P>\r\n");
      out.write("<h3>type: textarea</h3>\r\n");
      out.write("<textarea name=\"test\" rows=\"10\" cols=\"30\">\r\n");
      out.write("내용을 먼저 입력 할수 있어요.\r\n");
      out.write("</textarea>\r\n");
      out.write("<h3>type: select</h3>\r\n");
      out.write("<select name=\"fruit\" size=\"2\">\r\n");
      out.write("<option value=\"apple\">사과\r\n");
      out.write("<option value=\"banana\">바나나\r\n");
      out.write("<option value=\"peach\">복숭아\r\n");
      out.write("</select>\r\n");
      out.write("</FORM>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
