/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.59
 * Generated at: 2020-11-01 15:03:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class scripttest_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("자바스크립트 예문입니다<BR>\r\n");
      out.write("<script language=\"JAVASCRIPT\">\r\n");
      out.write("document.write(\"안녕하세요\")\r\n");
      out.write("</script><BR>\r\n");
      out.write("<!-- 자바스크립트로 글을쓴거다.. System.out.println(\"안녕하세요\")랄까?  -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("alert(\"행복하세요\")\r\n");
      out.write("</script>\r\n");
      out.write("<!--경고 메시지 박스(행복하세요) 생성-->\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("<!--\r\n");
      out.write("\tdocument.write(\"주석태그를 사용하였습니다.\")\r\n");
      out.write("\t-->\r\n");
      out.write("<!-- 예전에 익스플로러가 자바스크립트를 인식못할때 사용됫다 -->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("alert(\"안녕하세요. 환영합니다.\\nalert대화상자입니다.\")\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 안녕하세요. 환영합니다. \\n 개행 후 alert대화상자입니다. 경고박스 생성 -->\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("document.write(confirm(\"이 홈이 처음 방문 입니까?\"))\r\n");
      out.write("</script>\r\n");
      out.write("<!--  이 홈이 처음 방문 인지 (확인)(취소) 버튼과 함께 confirm 박스 생성 확인:true 취소:false 리턴-->\r\n");
      out.write("\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("prompt(\"이름을 입력하세요\")\r\n");
      out.write("</script><br>\r\n");
      out.write("<!--  문자를 입력받을수 있는 창이 하나 활성화된다 -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("<!--\r\n");
      out.write(" a=0\r\n");
      out.write(" d=\"하이\"\r\n");
      out.write(" b=20\r\n");
      out.write(" c=10+1\r\n");
      out.write(" f=\"안녕하세요 이것도 되나요\"\r\n");
      out.write(" aa=10\r\n");
      out.write(" bb=0x10 \r\n");
      out.write(" cc=010\r\n");
      out.write(" document.write(\"a=\"+a+\"<br>\")\r\n");
      out.write(" document.write(\"b=\"+b+\"<br>\")\r\n");
      out.write(" document.write(\"c=\"+c+\"<br>\")\r\n");
      out.write(" document.write(d)\r\n");
      out.write(" document.write(f+\"<br>\")\r\n");
      out.write(" document.write(\"=======================<br>\")\r\n");
      out.write(" document.write(\"2진수 aa: \"+aa+\"<br>\")\r\n");
      out.write(" document.write(\"16진수 bb: \"+bb+\"<br>\")\r\n");
      out.write(" document.write(\"10진수 cc: \"+cc+\"<br>\")\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- 단순하게 a = 0,b,c 를 하면 a=0이고 b랑 c도 변수로 쓸거다 라고함;; 자료형필요읍음 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
